# format = "[ ïŒ‚ ](bg:#8fbcbb fg:#3b4252)$directory($git_branch) $git_metrics\n$character"

# [character]
# success_symbol = "[â¯](bold #88c0d0)"
# error_symbol = "[â¯](bold #bf616a)"
# vicmd_symbol = "[â®](bold #5e81ac)"

# [battery]
# disabled = true

# [cmd_duration]
# format = "[$duration]($style)"
# style = 'bright-black'

# [directory]
# style = "#3b4252"
# format = "[î‚°](bg:#3b4252 fg:#8fbcbb)[ $path ](bg:#3b4252 fg:#d8dee9)[î‚°](fg:$style)"

# [git_branch]
# style = "#2e3440"
# format = "\b[î‚°](bg:$style fg:#3b4252)[ $branch ](bg:$style fg:#8fbcbb)[î‚°](fg:$style)"

# [git_metrics]
# disabled = false
# added_style = "green"
# deleted_style = "red"

# [git_status]
# style = "bright-black"

[aws]
disabled = true

# # [nodejs]
# # format = "via [ğŸ¤– $version](bold green) "

# # [package]
# # disabled = true

# # [ruby]
# # disabled = true

# # [lua]
# # disabled = true

# # [golang]
# # format = "via [ğŸğŸ’¨ $version](bold cyan) "

